include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: false
  exclude:
    - "**/generated/**.dart"
    - "**/**.config.dart"
    - "**/**.g.dart"

linter:
  rules:
    avoid_returning_this: true
    type_annotate_public_apis: true
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    package_api_docs: true
    package_prefixed_library_names: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unnecessary_lambdas: true
    require_trailing_commas: true
    prefer_final_in_for_each: true
    use_raw_strings: false
    prefer_single_quotes: true
    valid_regexps: true
    use_enums: true
    use_named_constants: true
    unnecessary_late: true
    use_string_buffers: true
    use_if_null_to_convert_nulls_to_bools: true
