name: whatsapp_redesign
version: 1.0.0+1
description: "WhatsApp Redesign"

publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  adaptive_layout:
    git:
      url: https://github.com/pintusingh28/flutter-packages
      path: adaptive_layout
  ui_components:
    git:
      url: https://github.com/pintusingh28/flutter-packages
      path: ui_components
  animations: ^2.0.11
  go_router: ^14.2.0
  provider: ^6.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^4.0.0

dependency_overrides:
  adaptive_layout:
    path: ../../Packages/flutter-packages/adaptive_layout

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/navigation/
    - assets/vectors/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: lib/src/presentation/localization/arb/
  output_dir: lib/src/presentation/localization/generated/
  use_deferred_loading: true